# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         JEvent
version:      0.11
version_from: JEvent.pm
installdirs:  site
requires:
    Data::UUID:                    0
    Net::SPOCP:                    0.10
    Net::XMPP:                     1.0-1
    XML::Stream:                   1.22-1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
