#!/usr/bin/env perl

use Getopt::Std;
use JEvent;

my $usage=<<EOU;
Usage: $0 [-h] -c agent.ini

$0 Sample JEvent agent

SYNOPSIS

\t-c\tINI-style configuration file for this agent.
\t-h\tShow this text

EOU

getopts('c:h');
die $usage if $opt_h;
die $usage unless $opt_c;

die $usage unless -f $opt_c;

my $ini = Config::IniFiles->new(-file=>$opt_c)
  or die "Unable to read configuration from $opt_c: $!\n";

my $host = Sys::Hostname::hostname();
my $je = JEvent->new(Config=>$ini,
		     Commands=>{
				shutdown => sub {
				  my ($self,$from,$type,$cmd,@args) = @_;
				  $self->LogInfo("Got shutdown from $_[1]");
				  warn "Got shutdown from $_[1]. Bye...\n";
				  exit;
				},
				pubsub => \&JEvent::cmd_pubsub,
                                list => sub {
                                  my ($self,$from,$type,$cmd,@args) = @_;

                                  $self->DiscoverNodes(Host=>$args[0],Node=>$args[1])->GetXML();
                                }
			       }
		     );

$je->Run();
