#!/usr/bin/env perl

use Getopt::Std;
use Config::IniFiles;
use JEvent::RDF;
use DCM;
use Unicode::String qw(latin1 utf8);

my $usage=<<EOU;
Usage: $0 [-h] -c agent.ini

$0 Sample JEvent agent

SYNOPSIS

\t-c\tINI-style configuration file for this agent.
\t-h\tShow this text

Apart from the common ini-parameters this agents expects information
about the connection to LDAP:

[LDAP]
Server=<ldap server>
SASLMech=SASL Mechanism (defaults to GSSAPI)
BindDN=<ldap DN to bind as>
EOU

getopts('c:h:t:');
die $usage if $opt_h;
die $usage unless $opt_c;

die $usage unless -f $opt_c;

my $ini = Config::IniFiles->new(-file=>$opt_c)
  or die "Unable to read $opt_c\n";
my $dcm = DCM::Secure::SASL->new($ini->val('LDAP','Server'),
				 version=>3,
				 BindDN=>$ini->val('LDAP','BindDN'));

my $host = Sys::Hostname::hostname();
my $je = JEvent::RDF->new(Config=>$ini,
			  Commands=>{
				     shutdown => sub {
				       my ($self,$from,$type,$cmd,@args) = @_;
				       $self->LogInfo("Got shutdown from $_[1]");
				       warn "Got shutdown from $_[1]. Bye...\n";
				       exit;
				     },
				    },
			  RDFCB => sub {
			    my ($self,$model) = @_;

			    warn $self->
			    my $reqs = $model->getContainerObjects("urn:x-su:jevent:directory");
			    return unless ref $reqs eq 'ARRAY';

			    foreach my $req (@{$reqs})
			      {
				
			      }
			  });

$je->Run();
